name: Docker Image CI

on:
  push:
    branches:
      - main

env:
  FRONTEND_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/frontend-action
  BACKEND_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/backend-action

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ env.FRONTEND_IMAGE }} ./frontend

      - name: Push the Docker image
        run: docker push ${{ env.FRONTEND_IMAGE }}

  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ env.BACKEND_IMAGE }} ./backend

      - name: Push the Docker image
        run: docker push ${{ env.BACKEND_IMAGE }}
